#ifndef WIDGETRY_CONFIG_H
#define WIDGETRY_CONFIG_H

#include <QtCore/qglobal.h>

#define WIDGETRY_VERSION_MAJOR 1
#define WIDGETRY_VERSION_MINOR 0
#define WIDGETRY_VERSION_PATCH 0
#define WIDGETRY_VERSION_STR   "1.0.0"
#define WIDGETRY_VERSION       WIDGETRY_VERSION_CHECK(WIDGETRY_VERSION_MAJOR, WIDGETRY_VERSION_MINOR, WIDGETRY_VERSION_PATCH)
#define WIDGETRY_VERSION_CHECK QT_VERSION_CHECK

#endif // WIDGETRY_CONFIG_H
